# Generated by Django 5.0 on 2023-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wedlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('profile_seeking_for', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=10)),
                ('mother_tongue', models.CharField(max_length=10)),
            ],
        ),
    ]
